[bar/mybar]
enable-ipc = true
width = 100%
height = 48
bottom = true
padding = 2
background = #303446
foreground = #FFFFFF
separator = "  "
font-0 = "Cascadia Code:size=18;5"


modules-left  = filesystem memory cpu
modules-right = battery pulseaudio date ewmh

; Battery module
[module/battery]
type = custom/script
exec = ~/.config/polybar/battery.sh
interval = 60

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = true
interval = 5
reverse-scroll = false
label-volume = [VOL %percentage%%]
format-muted = [VOL MUT]

[module/memory]
type = internal/memory
interval = 3
label = [RAM %gb_used%/%gb_total%]

[module/filesystem]
type = internal/fs
mount-0 = /
label-mounted = [DISK %used%/%total%]

[module/cpu]
type = internal/cpu
interval = 0.5
label = [CPU %percentage%%]

[module/date]
type = internal/date
date = %a %d.%m.%Y
time = %H:%M
label = [%date% ~ %time%]

[module/ewmh]
type = internal/xworkspaces
pin-workspaces = true
group-by-monitor = false
enable-click = false
enable-scroll = false
reverse-scroll = true
format = [<label-state>]
label-active = %name%
label-empty = %name%
label-occupied = %name%
label-active-foreground = #ffffff
label-active-background = #414559
label-active-underline = #fba922
label-active-padding = 1
label-empty-padding = 1
label-occupied-padding = 1

